### ISSUE TITLE
Skript > MyCommand

### ISSUE THREAD

**Issue by Orendigo** [CptShock/Polygoncraft#58]
[Skript](http://dev.bukkit.org/bukkit-plugins/skript/) is just what it sounds like- it's a plugin capable of creating and running complex scripts.  Skript can do many things, one of which is create custom commands- which is why I ask we switch from MyCommand to Skript.

Skript has ample potential to benefit Poly; rather than spend time explaining how Skript exceeds MyCommand, I will instead list a few Skript abilities and their MyCommand counterparts:

Script Statements:
    MyCommand: Limits to 1 if-statement for one command
    Skript: Limitless if-statements, else-if statements, and while-statements

Aliases:
    MyCommand: One aliases for each command
    Skript: Capable of one command to wield multiple aliases

Limites:
    MyCommand: Limited to creating commands
    Skript: Can run scripts not only from commands, but from over 600 event, such as 'on build'

Variables:
    MyCommand: What's a variable?
    Skript: Can use local-variables for one event only; variables which can be access from other scripts, and list-variables.

Skript is just a better alternative to MyCommand in the long run.

The list of events, conditions, effects, and expressions for Skript can be found [here](http://www.skunity.com/search?search=)

**Comment by Flexo013** [comment]
Implemented
